---
title: "Prepare SARI data"
prerequisites:
    - data/cleaned/clean_data_srag_epiweek_delay_table_PR.csv
targets:
    - data/processed/sari_cum_2009_06_14_to_11_22.rds
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
knitr::opts_chunk$set(fig.height = 8, fig.width = 6, out.width = "100%")
knitr::opts_chunk$set(comment = "#>")
options(width = 100)
```

## Load packages, scripts and data

```{r}
path_proj <- here::here()
path_src <- file.path(path_proj, "src")
path_data <- file.path(path_proj, "data")
path_cleaned <- file.path(path_data, "cleaned")
path_processed <- file.path(path_data, "processed")

library(dplyr)
library(aweek)
library(tidyr)

source(file.path(path_src, "process-data.R"))

sari <- path_cleaned |>
    file.path("clean_data_srag_epiweek_delay_table_PR.csv") |>
    readr::read_csv()
```

## Process data

- Standardise variable names,
- create the date of the week and year,
- filter a region of interest $41002$ and
- filter dates of interest from `2009-06-14` to `2009-11-22`.

```{r}
date_period <- as.Date(c("2009-06-14", "2009-11-22"))
sari_41002 <- sari |>
    rename_with(tolower) |>
    mutate(date = get_date(week = epiweek, year = epiyear, start = 7)) |>
    filter(regionalsaude == 41002, date >= date_period[1], date <= date_period[2]) |>
    select(- c("epiweek", "epiyear", "regionalsaude")) |>
    rename_with(function(x) gsub("d", "delay", x), d0:d26) |>
    relocate(notifications_within_26w, notifications, .after = last_col())
```

Compute the cumulative number of cases.

```{r}
sari_41002[, 1:27] <- t(apply(as.matrix(sari_41002[, 1:27]), 1, cumsum))
sari_41002
```

## Save processed data

```{r}
saveRDS(sari_41002, file.path(path_processed, "sari_cum_2009_06_14_to_11_22.rds"))
```

## Time to execute the task

Only useful when executed with `Rscript`.

```{r}
proc.time()
```

