---
title: "Exploratory analysis hus0104"
output: html_document
makefile: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE)
```

## Load packages and data

```{r setup, include=FALSE}
library(splines)
library(ggplot2)
library(reshape2)
library(aweek)
library(dplyr)
library(tidyr)
library(latex2exp)

path_proj <- here::here()
path_source <- file.path(path_proj, "source")

sari <- as.data.frame(read.csv(file.path(path_proj, "data", "raw", "clean_data_srag_epiweek_delay_table_PR.csv"),))

# set week
set_week_start("Sunday")
sari$date <- get_date(week = sari$epiweek, year = sari$epiyear)
```

## Filter dates of interest

```{r, warning=FALSE}
# region 41002
data_41002 <- sari |> filter(regionalsaude == 41002) |>
  select(-c("epiweek","epiyear","regionalsaude")) |>
  relocate(Notifications, .after = last_col())
rownames(data_41002) <- data_41002$date

#transfer to cumu matrix
data_41002[,c(1:27)] <- t(apply(as.matrix(data_41002[,c(1:27)]), 1, cumsum))

date_range <- as.Date(c("2009-06-14", "2009-11-22"))
data_41002 <- data_41002 |>
  filter(date >= date_range[1] & date <= date_range[2]) |>
  select(-Notifications_within_26w, -Notifications)

df <- data_41002 |>
    pivot_longer(matches("^d[0-9]+"), names_to = "delay", values_to = "cases",
                 names_transform = function(x) as.numeric(sub("d", "", x))) |>
    mutate(available_delay = floor(as.numeric(date_range[2] - date) / 7 )) |>
    filter(delay <= available_delay)
```

## Fit Exponential and Gompertz curves

```{r}
# prepare data
somedates <- seq(as.Date("2009-07-19"), as.Date("2009-09-06"), "1 week")
df_check <- filter(df, date %in% somedates) |>
    mutate(date = factor(date))
df_fit <- data.frame(delay = seq(0, max(df_check$delay), length = 100))

aux <- df_check |>
    group_by(date) |>
    summarise(cases = max(cases))

# models
mod_gomp <- nls(cases ~ exp(logN[date]) * exp(logphi*exp(-b * delay)), data = df_check,
    start = list(b = 0.5, logphi = log(0.05), logN = log(aux$cases)))
#    start = list(b = 0.5, logphi = log(0.05), logN = rep(log(50), length(unique(df_check$date)))))
#    start = list(b = 0.5, logphi = log(0.05), logN = rep(log(50), length(unique(df_check$date)))))

mod_exp <- nls(cases ~ exp(logN[date]) * (1 - plogis(logitphi)* exp(-b * delay)), data = df_check,
    start = list(b = 0.5, logitphi = qlogis(0.9), logN = log(aux$cases)))

sapply(list(Exponential = mod_exp, Gompertz = mod_gomp),
       function(x) c(AIC = AIC(x), BIC = BIC(x), SSE = deviance(x))) |>
    data.frame()

#     Exponential   Gompertz
# AIC    1224.285   1260.084
# BIC    1255.308   1291.107
# SSE  117977.984 157464.601

# predict
df_check <- df_check |>
    mutate(gomp_total = exp(coef(mod_gomp)[-(1:2)])[as.integer(df_check$date)],
           gomp_q = cases / gomp_total,
           exp_total = exp(coef(mod_exp)[-(1:2)])[as.integer(df_check$date)],
           exp_q = cases / exp_total
    ) |>
    pivot_longer(gomp_total:exp_q, names_to = c("model", "var"), names_pattern = "(.*)_(.*)") |>
    pivot_wider(names_from = var, values_from = value)

df_fit <- df_fit |>
    mutate(gomp_q = exp(coef(mod_gomp)["logphi"] * exp(-coef(mod_gomp)["b"] * delay)),
           exp_q = 1 - plogis(coef(mod_exp)["logitphi"]) * exp(-coef(mod_exp)["b"] * delay)
    ) |>
    pivot_longer(gomp_q:exp_q, names_to = c("model"), values_to = "q",
                 names_transform = function(x) sub("_q", "", x)
    )

# visualize
mylabs <- c("exp" = "(a) Exponential", "gomp" = "(b) Gompertz")
p <- ggplot(df_check) +
    geom_line(aes(delay, q, group = date), color = "gray", linewidth = rel(0.3)) +
    geom_point(aes(delay, q, group = date, color = "Empirical"), size = rel(0.5)) +
    geom_line(aes(delay, q, color = "Theoretical"), df_fit, linewidth = rel(0.5), linetype = "dashed") +
    labs(title = NULL, y = TeX("$q(d)$"), x = TeX("$d$"), color = NULL) +
    facet_wrap(~ model, scales = "free", labeller = as_labeller(mylabs)) +
    theme_classic(9) +
    scale_colour_manual(values = c("gray30", "red")) +
    theme(
        legend.position = c(0.9, 0.15),
        strip.background = element_blank(),
        strip.text = element_text(face = "bold")
    )
ggsave(filename = file.path(path_proj, "plots_to_show", "qd_emp_fit_sari.png"),
       plot = p,
       width = 20 * 8/ 20, height = 8 * 8 / 20, dpi = 300)
```
